checkPrototypes: tolerate unstringifyable prototypes
The prototype of an async function, in particular, refuses to be stringified
normally. `${(async _ => _).__proto__}` throws an error. In Node, this looks
like:

```
TypeError: Function.prototype.toString requires that 'this' be a Function
```